taps:
  - AdoptOpenJDK/openjdk
  - mas-cli/tap
  - homebrew/cask-versions
packages:
  - { name: git }
  - { name: tig }
  - { name: mercurial }
  - { name: tree }
  - { name: wget }
  - { name: go }
  - { name: tmux }
  - { name: curl }
  - { name: yarn }
  - { name: ag }
  - { name: gdub }
  - { name: ghq }
  - { name: fzf }
  - { name: dep }
  - { name: fish }
  - { name: pyenv }
  - { name: openssl }
  - { name: fontconfig }
  - { name: mas }
cask_packages:
  - { name: caffeine }
  - { name: adoptopenjdk8 }
  - { name: alfred }
  - { name: google-chrome }
  - { name: google-chrome-canary }
  - { name: google-cloud-sdk }
  - { name: google-japanese-ime }
  - { name: android-studio }
  - { name: webstorm }
  - { name: keyboardcleantool }
  - { name: virtualbox }
  - { name: gimp }
  - { name: karabiner-elements }
  - { name: google-backup-and-sync }
  - { name: flux }
  - { name: slack }
  - { name: vagrant }
  - { name: visual-studio-code }
  - { name: vlc }
  - { name: insomnia }
  - { name: hyper }
  - { name: charles }
  - { name: docker }
  - { name: chromium }
  - { name: qfinder-pro }
